trigger:
  branches:
    include:
      - main
      - feature/*

pool: SonarQube-SelfHosted

stages:

- stage: Build
  displayName: Build React App

  jobs:
  - job: BuildJob
    displayName: Build and Publish

    steps:
    - template: template/build-react.yml
      parameters:
        nodeVersion: '20.x'

